// 各种请求状态
// 


//获取图表信息
export const GET_ECHARTS_ORDERS = 'GET_ECHARTS_ORDERS';
export const GET_ECHARTS_ORDERS_REQUEST = 'GET_ECHARTS_ORDERS_REQUEST';
export const GET_ECHARTS_ORDERS_SUCCESS = 'GET_ECHARTS_ORDERS_SUCCESS';
export const GET_ECHARTS_ORDERS_FAILURE = 'GET_ECHARTS_ORDERS_FAILURE';